### PR TITLE
Add search on the main page

### LINKED ISSUE #11: Add search on the main page
it should search in method/class names

### PR DESCRIPTION
**Pull request by BuonOmo**
Closes #11 

Screen-Recording-2021-05-30-at-2

The string score algorithm I used is similar to what is used in Atom or VSCode, hence it should feel familiar to devs.

### CODE REVIEW

**Comment by alisnic** [comment]
@BuonOmo I have to confess I don't remember what I really meant when I created that issue xD Can you share from your experience what benefit will this feature have over just searching the page via `cmd-f` ?

**Comment by BuonOmo** [comment]
@alisnic it is a bit more advanced (allowing to search by acronyms, or missing keys), however, I really just read the issue and try to match it correctly...

Two ideas:
- I could map `ctrl`+`f` to this (once, the second time it goes to the browser)
- We can just wait to see if someone else is interested in that idea

**Comment by BuonOmo** [comment]
@alisnic just used the gem once again, and having a better algorithm than the basic chrome full string search would have been useful for searching for similar names in the stack.

With that said, this maybe is the role of a chrome extension rather than a search tool per web page..

**Comment by alisnic** [comment]
Hey @BuonOmo, sorry I didn't get the chance to write here. It's been difficult because I'm thorn internally about this merge request. From one hand I want to be respectful and encouraging of your efforts, but on the other hand I'm trying to understand whether this change will benefit the project in a meaningful way

So basically now I'm blocked trying to understand what to do with this merge request

**Comment by BuonOmo** [comment]
@alisnic thank you for being kind, yet if you close the PR I'll understand, no worries!

I suggest waiting 🙂

**Comment by alisnic** [comment]
Actually it doesn't hurt anyone to have this merged so I'll go with it 🚀

**Pull request merged**
